# Generated by Django 5.2.3 on 2025-06-17 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0004_alter_warehouse_capacity_alter_warehouse_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='products/%y/%m/%d')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.warehouse')),
            ],
        ),
    ]
