# Generated by Django 5.2.3 on 2025-06-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_warehouse_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
